# Generated by Django 5.0.8 on 2024-08-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='persona',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='producto',
            field=models.CharField(max_length=100),
        ),
    ]
